# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/new/Vivado/Vivado/final/record/Record_mode/Record_mode.cache/wt [current_project]
set_property parent.project_path D:/new/Vivado/Vivado/final/record/Record_mode/Record_mode.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {{d:/new/Vivado/Vivado/final/record/Keyboard Sample Code/ip/Keyboard-Controller/keyboard_cntr_1.0}} [current_project]
add_files d:/new/Vivado/Vivado/final/record/out.coe
add_files -quiet d:/new/Vivado/Vivado/final/record/Record_mode/Record_mode.srcs/sources_1/ip/KeyboardCtrl_0/KeyboardCtrl_0.dcp
set_property used_in_implementation false [get_files d:/new/Vivado/Vivado/final/record/Record_mode/Record_mode.srcs/sources_1/ip/KeyboardCtrl_0/KeyboardCtrl_0.dcp]
read_ip -quiet d:/new/Vivado/Vivado/final/record/Record_mode/Record_mode.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all d:/new/Vivado/Vivado/final/record/Record_mode/Record_mode.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]
set_property is_locked true [get_files d:/new/Vivado/Vivado/final/record/Record_mode/Record_mode.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci]

read_verilog -library xil_defaultlib {
  D:/new/Vivado/Vivado/final/record/Record_mode/Record_mode.srcs/sources_1/imports/record/pixel.v
  D:/new/Vivado/Vivado/final/record/Record_mode/Record_mode.srcs/sources_1/imports/record/Recording.v
  D:/new/Vivado/Vivado/final/record/Record_mode/Record_mode.srcs/sources_1/imports/record/PWM.v
  {D:/new/Vivado/Vivado/final/record/Record_mode/Record_mode.srcs/sources_1/imports/record/Keyboard Sample Code/OnePulse.v}
  D:/new/Vivado/Vivado/final/record/Record_mode/Record_mode.srcs/sources_1/imports/record/seven_segments.v
  D:/new/Vivado/Vivado/final/record/Record_mode/Record_mode.srcs/sources_1/imports/record/vga.v
  D:/new/Vivado/Vivado/final/record/Record_mode/Record_mode.srcs/sources_1/imports/record/plyer_control.v
  D:/new/Vivado/Vivado/final/record/Record_mode/Record_mode.srcs/sources_1/imports/record/onepulse.v
  D:/new/Vivado/Vivado/final/record/Record_mode/Record_mode.srcs/sources_1/imports/record/KeysDecord.v
  D:/new/Vivado/Vivado/final/record/Record_mode/Record_mode.srcs/sources_1/imports/record/dedounced.v
  D:/new/Vivado/Vivado/final/record/Record_mode/Record_mode.srcs/sources_1/imports/record/clock_divider.v
  {D:/new/Vivado/Vivado/final/record/Record_mode/Record_mode.srcs/sources_1/imports/record/Keyboard Sample Code/KeyboardDecoder.v}
  D:/new/Vivado/Vivado/final/record/Record_mode/Record_mode.srcs/sources_1/imports/record/Timer.v
  D:/new/Vivado/Vivado/final/record/Record_mode/Record_mode.srcs/sources_1/imports/record/test.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/new/Vivado/Vivado/final/record/Record_mode/Record_mode.srcs/constrs_1/imports/record/Basys3_Master.xdc
set_property used_in_implementation false [get_files D:/new/Vivado/Vivado/final/record/Record_mode/Record_mode.srcs/constrs_1/imports/record/Basys3_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top Record_mode -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Record_mode.dcp

catch { report_utilization -file Record_mode_utilization_synth.rpt -pb Record_mode_utilization_synth.pb }
