# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/new/Vivado/Vivado/final/test2/test2/test2.cache/wt [current_project]
set_property parent.project_path D:/new/Vivado/Vivado/final/test2/test2/test2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {D:/new/Vivado/Vivado/final/test2/test2/test2.srcs/sources_1/imports/demo1 piano/PWM_gen.v}
  {D:/new/Vivado/Vivado/final/test2/test2/test2.srcs/sources_1/imports/demo1 piano/TOP.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/new/Vivado/Vivado/final/test2/test2/test2.srcs/constrs_1/imports/demo1 piano/constraints.xdc}}
set_property used_in_implementation false [get_files {{D:/new/Vivado/Vivado/final/test2/test2/test2.srcs/constrs_1/imports/demo1 piano/constraints.xdc}}]


synth_design -top TOP -part xc7a35tcpg236-1


write_checkpoint -force -noxdef TOP.dcp

catch { report_utilization -file TOP_utilization_synth.rpt -pb TOP_utilization_synth.pb }
